url: YOUR_DOMAIN
title: Houtouwan
description: This is a template for creating directories
header_text: "This is a template for creating directories" # Text for the main header of the website
footer_text_1: "This is a right footer" # Right footer text
footer_text_2: "This is a left footer" # Left footer text
header_image: "/assets/images/example.jpg"
content_image: "/assets/images/example.jpg"
place_link_text: "Visit this place" # The link text to go directly to the location, which will appear on the location details page.
locale: en_US
author:
  twitter: YOUR_TWITTER_ACCOUNT
  name: Houtouwan
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
twitter:
  username: YOUR_TWITTER_ACCOUNT
  card: summary_large_image
airtable:
  token: "patSMaP1gaN9TOAfz.878c2e700636bf3e34f5fec4d508fb0e72c3af2d3afe43366e4f74426589c896"
  base_id: "appszGRwxOuju9sYi"
social:
  name: Houtouwan
  links:
    # - https://twitter.com/houtouwan
    # - https://www.instagram.com/houtouwan
    # - https://www.linkedin.com/company/houtouwan
fonts:
  - url: "https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
    type: "google"
  - url: "/assets/fonts/InstrumentSerif-Regular.woff2"
    type: "woff2"
paragraph_font: "'Open Sans', serif"
title_font: "'Open Sans', serif"
postcss:
  cache: false
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/example.jpg
