url: "https://crearespaces.com"
title: "Creare"
description: "Spaces to be creative and to work remotely around the world"
author:
  twitter: crearespaces
  name: Creare Spaces
  picture: /assets/images/me.jpg
collections:
  recommendations:
    output: true
    permalink: /recommendations/:name
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

postcss:
  cache: false
