url: "https://albertogalca.com"
title: "Alberto's nonsense"
description: "I create software, write random stuff, and enjoy traveling to capture moments with my phone"
author:
  twitter: albertogalca
  name: Alberto Gallego
  picture: /assets/images/me.jpg
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed

postcss:
  cache: false
