url: YOUR_DOMAIN
title: Houtouwan
description: This is a template for creating directories
header_text: "This is a template for creating directories"
footer_text_1: "This is a right footer"
footer_text_2: "This is a left footer"
header_image: "/assets/images/example.jpg"
content_image: "/assets/images/example.jpg"
locale: en_US
author:
  twitter: YOUR_TWITTER_ACCOUNT
  name: Houtouwan
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
twitter:
  username: YOUR_TWITTER_ACCOUNT
  card: summary_large_image
airtable:
  token: "patSMaP1gaN9TOAfz.878c2e700636bf3e34f5fec4d508fb0e72c3af2d3afe43366e4f74426589c896"
  base_id: "appszGRwxOuju9sYi"
social:
  name: Houtouwan
  links:
    # - https://twitter.com/crearespaces
    # - https://www.instagram.com/crearespaces
    # - https://www.linkedin.com/company/crearespaces
postcss:
  cache: false
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/example.jpg
